### ISSUE TITLE
Very cool program, but is this a virus?

### ISSUE THREAD

**Issue by odorizzioficial** [hedihadi/zal#9]
Incredible application friend, but the zal.sys file I checked on virustotal and two viruses appeared and I was scared :/

![image](https://github.com/user-attachments/assets/2796cc96-bf3a-4e1a-b5e3-caec8e09aec4)

**Comment by hedihadi** [comment]
hello, it's not a virus but my word is like "dude trust me". 

you can download presentmon from the official github
https://github.com/GameTechDev/PresentMon
and check presentmon.exe using virustotal, you get similar flags.

these are just random anti viruses that understandably pickup "suspecious behavior" from the program, which is expected. because the program literally runs commands behind the scenes to get hardware data, and sends that data to your phone using the internet. but the anti virus doesn't know that the data is being sent to YOUR phone, so it basically tells you "something might be wrong here".

again, the program is fully open source, you can download the source code and run it from there. you can check all the codes and i'm pretty sure you won't find any virus. it's not a complex project to be honest, if you're a programmer you can surf through it in a couple hours.

**Comment by odorizzioficial** [comment]
I understand friend, thank you very much for clarifying, nowadays it is difficult to download something, but thank you very much for being honest

**Comment by odorizzioficial** [comment]
Hello, when deleting the Portable folder, zal.sys does not allow it to be deleted, only if I restart the computer, how do I find it in the task manager to finish?  because I didn't find it

**Comment by hedihadi** [comment]
> Hello, when deleting the Portable folder, zal.sys does not allow it to be deleted, only if I restart the computer, how do I find it in the task manager to finish? because I didn't find it

to delete the Zal.sys, you have to stop these processes in task manager
* presentmon.exe
* process_getter.exe
* Zal.exe

**Comment by hedihadi** [comment]
i'll close this issue because the original question seems to be resolved, thank you!
